### ISSUE TITLE
Request: Please have skeleton test script for the node template so all the TS and other configs for writing tests is in place.

### ISSUE THREAD

**Issue by technomage** [restatedev/node-template-generator#18]
It would be helpful to encourage testing, and to have the template set up the build (in particular for those not as familiar with typescript build proceses.  It would also help to have examples of unit tests or integration tests for restate services.

**Comment by tillrohrmann** [comment]
Related to https://github.com/restatedev/sdk-typescript/issues/101.

**Comment by slinkydeveloper** [comment]
Hey @technomage, I have an update about this issue. I've been experimenting a bit with testcontainers and i managed to put together a more or less working example: https://github.com/restatedev/node-template-generator/pull/19

But to get it right we probably need to implement some changes in sdk-typescript first.

**Comment by slinkydeveloper** [comment]
Hi @technomage I added an example in https://github.com/restatedev/examples/tree/main/typescript/end-to-end-testing that shows you how to test your service with testcontainers, hope it helps!
